#!/usr/bin/env python3
"""Shrink the type-based graph hubs to unclassified notes only.

Rationale: `graph-hubs/Meeting Evidence.md` linked 720 notes, producing a single
star that dominated the graph. Notes that now carry a `workstream:` property are
already linked from their workstream MOC, so their row here is a duplicate edge.
Dropping those rows turns each hub into a triage queue of what still needs
classifying, and lets the 8 workstream constellations become the graph's shape.

Rows whose target has no workstream are KEPT -- otherwise those notes would
become orphans and disappear under `showOrphans: false`.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from urllib.parse import unquote

VAULT = Path(__file__).resolve().parents[2]
HUB_DIR = VAULT / "5. Trackers" / "graph-hubs"

ROW = re.compile(r"^\|\s*\[(?P<label>[^\]]*)\]\((?P<target>[^)]+)\)\s*\|")


def has_workstream(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:800]
    except OSError:
        return False
    if not head.startswith("---"):
        return False
    end = head.find("\n---", 3)
    body = head[3:end] if end != -1 else head
    return bool(re.search(r"^workstream:\s*\S+", body, re.M))


def resolve(hub: Path, target: str) -> Path | None:
    if target.startswith(("http://", "https://", "#")):
        return None
    clean = unquote(target.split("#")[0].split("|")[0])
    return (hub.parent / clean).resolve()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    grand_kept = grand_dropped = 0
    for hub in sorted(HUB_DIR.glob("*.md")):
        text = hub.read_text(encoding="utf-8", errors="ignore")
        out, kept, dropped = [], 0, 0
        for line in text.splitlines():
            m = ROW.match(line)
            if not m:
                out.append(line)
                continue
            target = resolve(hub, m.group("target"))
            # Keep the row unless the target is already covered by a workstream MOC.
            if target and target.exists() and has_workstream(target):
                dropped += 1
                continue
            out.append(line)
            kept += 1

        if dropped:
            note = (f"\n> Pruned {dropped} rows already linked from their workstream MOC. "
                    f"Remaining {kept} rows are unclassified and need a `workstream:` value.")
            body = "\n".join(out)
            if "> Pruned" not in body:
                body = body.replace(
                    "> Generated by `/vacuum`.",
                    "> Generated by `/vacuum`." + note, 1)
            if args.apply:
                hub.write_text(body.rstrip("\n") + "\n", encoding="utf-8")

        if kept or dropped:
            print(f"{hub.stem:36s} kept {kept:4d}  dropped {dropped:4d}")
        grand_kept += kept
        grand_dropped += dropped

    print(f"\ntotal kept {grand_kept}, dropped {grand_dropped}")
    print("APPLIED" if args.apply else "DRY RUN (no files modified)")


if __name__ == "__main__":
    main()
