"""
Setup Wizard (FTUE)

Interactive script to initialize the Beats PM Brain.
Collects user context and populates SETTINGS.md.
"""

import sys
import os
from pathlib import Path

# Path setup
CURRENT_FILE = Path(__file__).resolve()
SYSTEM_ROOT = CURRENT_FILE.parent.parent      # system/
BRAIN_ROOT = SYSTEM_ROOT.parent               # brain/

# Add BRAIN_ROOT to path for imports
sys.path.insert(0, str(BRAIN_ROOT))

from system.utils.ui import print_cyan, print_green, print_yellow, print_success, print_error
from system.utils.filesystem import file_exists
from system.utils.config import get_path

def ask(question, default=None):
    """Ask a question with an optional default."""
    prompt = f"{question} "
    if default:
        prompt += f"[{default}]: "
    else:
        prompt += ": "
    
    response = input(prompt).strip()
    return response if response else default

def generate_settings(context):
    """Generate SETTINGS.md Content."""
    return f"""# SYSTEM SETTINGS (User Preferences)

> **Auto-Generated by Setup Wizard**

## 1. Context
- **Name**: {context['name']}
- **Role**: {context['role']}
- **Company**: {context['company']}
- **Team**: {context['team']}

## 2. Key Products
- {context['product']}

## 3. Leadership
- **Direct Manager**: {context['boss']}
- **Strategy Anchor**: {context['strategy']}

## 4. Preferences
- **Timezone**: {context['timezone']}
- **Work Hours**: 09:00 - 17:00
"""

def main():
    print_cyan("\n🧠 Beats PM Brain - Initialization Wizard")
    print_cyan("=========================================")
    print("Let's configure your digital second brain.\n")

    settings_path = BRAIN_ROOT / "SETTINGS.md"
    
    if settings_path.exists():
        print_yellow("SETTINGS.md already exists.")
        overwrite = ask("Overwrite? (y/n)", "n").lower()
        if overwrite != 'y':
            print("Skipping configuration.")
            # Run core verify anyway
            script_path = SYSTEM_ROOT / "scripts" / "core_setup.py"
            os.system(f'python "{script_path}"')
            return

    # Collect Data
    context = {}
    context['name'] = ask("What is your Name?", "PM")
    context['role'] = ask("What is your Role?", "Product Manager")
    context['company'] = ask("Company Name?", "Acme Corp")
    context['team'] = ask("Team Name?", "Core Product")
    context['product'] = ask("Primary Product you manage?", "The App")
    context['boss'] = ask("Who is your Direct Manager (for Boss Tracker)?", "The Boss")
    context['strategy'] = ask("One-line Strategy/Goal?", "Grow 10x")
    context['timezone'] = ask("Timezone?", "UTC")

    # Write File
    try:
        with open(settings_path, 'w', encoding='utf-8') as f:
            f.write(generate_settings(context))
        print_success("\n✅ SETTINGS.md assigned.")
    except Exception as e:
        print_error(f"Failed to write settings: {e}")
        return

    # Trigger Core Setup
    print_cyan("\n⚙️  Running System Core Setup...")
    script_path = SYSTEM_ROOT / "scripts" / "core_setup.py"
    # Using --headless for core_setup since we are already in an interactive session
    # but core_setup asks about extensions, which is good to keep interactive here?
    # Actually, let's keep it interactive for extensions.
    os.system(f'python "{script_path}"')

    print_green("\n🎉 Setup Complete!")
    print("Type `/track` to verify your environment.")

if __name__ == "__main__":
    main()
