"""
Generate promoted Codex skill adapters from the repo command registry.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from system.utils.command_registry import get_promoted_codex_commands


def get_codex_skills_dir(output_dir: str | None = None) -> Path:
    """Resolve the target directory for local Codex skills."""
    if output_dir:
        return Path(output_dir).expanduser()

    codex_home = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))
    return codex_home / "skills"


def render_skill_description(command):
    """Render a trigger-friendly one-line Codex skill description."""
    triggers = [f"`/{command['name']}`"] + [f"`/{alias}`" for alias in command["aliases"]]
    trigger_text = ", ".join(triggers)
    return (
        f"Run the Beats PM {trigger_text} workflow for the active Beats PM repo. "
        f"Use when the user invokes one of those commands or asks for {command['description'].rstrip('.').lower()}."
    )


def render_skill_md(command, repo_root: Path) -> str:
    """Render the SKILL.md for one promoted Codex command adapter."""
    supporting_lines = "\n".join(
        f"   - `<repo>/{path}`" for path in command["codex_supporting_files"]
    )
    optional_lines = "\n".join(
        f"   - `<repo>/{path}`" for path in command["codex_optional_files"]
    )
    if not supporting_lines:
        supporting_lines = "   - No extra supporting files are required by default."

    workflow_steps = [
        "1. Resolve the repo path first and use that same path for every file read below.",
        f"2. Read `<repo>/.agent/workflows/{command['name']}.md`.",
        "3. Read the minimum supporting files needed for execution:",
        supporting_lines,
    ]
    if optional_lines:
        workflow_steps.extend(
            [
                "4. Read optional files only when they exist:",
                optional_lines,
                "5. If an optional file is missing, continue without it and note that briefly.",
                f"6. If the user typed `/{command['name']}` or one of its aliases, treat the remaining text as workflow input.",
                "7. Follow the repo workflow instead of inventing a parallel Codex-only process.",
                "8. Keep durable output inside the repo so Antigravity and Codex share the same state.",
            ]
        )
    else:
        workflow_steps.extend(
            [
                f"4. If the user typed `/{command['name']}` or one of its aliases, treat the remaining text as workflow input.",
                "5. Follow the repo workflow instead of inventing a parallel Codex-only process.",
                "6. Keep durable output inside the repo so Antigravity and Codex share the same state.",
            ]
        )

    workflow_block = "\n".join(workflow_steps)
    contract_lines = "\n".join(
        f"{index}. {line}" for index, line in enumerate(command.get("codex_execution_contract", []), start=1)
    )
    contract_block = ""
    if contract_lines:
        contract_block = f"""
## Execution Contract

{contract_lines}
"""
    safety_block = ""
    if command["dangerous"]:
        note = command["note"] or "This command is state-changing. Inspect the current repo state before running it."
        safety_block = f"""
## Safety

- This command is intentionally available in Codex, but it is state-changing.
- Treat an explicit `/{command["name"]}` invocation as user intent to run it, not just discuss it.
- Before execution, inspect the current repo state that could be affected.
- {note}
- If the risk is material and immediate, explain it briefly before continuing.
"""

    return f"""---
name: {command["codex_skill_name"]}
description: {render_skill_description(command)}
---

# {command["codex_skill_name"]}

> Auto-generated by `system/scripts/sync_codex_skill_adapters.py`.
> Source of truth: `.agent/workflows/{command["name"]}.md` + `.agent/command-registry.json`

Use this skill only for a Beats PM kit repo.

## Repo Resolution

1. Prefer the current workspace when it contains all of:
   - `AGENTS.md`
   - `.agent/workflows/{command["name"]}.md`
2. Otherwise fall back to `{repo_root}`.
3. If neither location matches, say this skill requires a Beats PM kit repo and stop.
{safety_block}
{contract_block}

## Workflow

{workflow_block}
"""


def sync_promoted_skills(output_dir: str | None = None, root: Path | str | None = None):
    """Write the promoted skill adapters into the target Codex skills directory."""
    repo_root = Path(root) if root is not None else ROOT
    skills_dir = get_codex_skills_dir(output_dir)
    skills_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for command in get_promoted_codex_commands(repo_root):
        skill_dir = skills_dir / command["codex_skill_name"]
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_path = skill_dir / "SKILL.md"
        skill_path.write_text(render_skill_md(command, repo_root), encoding="utf-8")
        generated.append(command["codex_skill_name"])

    return generated


def main():
    parser = argparse.ArgumentParser(description="Sync promoted Beats Codex skill adapters")
    parser.add_argument(
        "--output-dir",
        help="Override Codex skills output directory (defaults to $CODEX_HOME/skills or ~/.codex/skills)",
        default=None,
    )
    args = parser.parse_args()

    generated = sync_promoted_skills(output_dir=args.output_dir)
    print(f"Generated {len(generated)} Codex skill adapter(s):")
    for skill_name in generated:
        print(f"  - {skill_name}")


if __name__ == "__main__":
    main()
