#!/usr/bin/env python3
"""Generate local CLI adapters from the canonical .agent tree.

The kit treats .agent/ as the source of truth. Runtime-specific adapter files are
thin pointers or local ignored directories so Codex, Gemini, Claude, and Kilo can
run without duplicating the canonical workflow definitions in Git.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
AGENT_DIR = ROOT / ".agent"
sys.path.insert(0, str(ROOT / "system"))

from utils.command_registry import (
    build_command_catalog,
    get_promoted_codex_commands,
    get_workflow_descriptions as registry_workflow_descriptions,
)
from scripts import generate_registry_docs


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        remove_path(path)
    if path.exists() and not path.is_symlink() and read_text(path) == content:
        return False
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    return True


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def workflow_files() -> list[Path]:
    return [
        AGENT_DIR / "workflows" / f"{name}.md"
        for name, _description in get_workflow_descriptions()
    ]


def skill_files() -> list[Path]:
    return sorted((AGENT_DIR / "skills").glob("*/SKILL.md"))


def agent_files() -> list[Path]:
    return sorted((AGENT_DIR / "agents").glob("*.md"))


def get_workflow_descriptions() -> list[tuple[str, str]]:
    return registry_workflow_descriptions(ROOT)


def get_command_catalog() -> list[dict[str, str | bool]]:
    return build_command_catalog(ROOT)


def get_promoted_command_catalog() -> list[dict[str, str | bool | list[str]]]:
    return get_promoted_codex_commands(ROOT)


def codex_adapter_label(item: dict[str, str | bool | list[str]]) -> str:
    if item["codex_promotion"] != "skill":
        return "Dispatch only"
    label = "Guarded skill" if item["dangerous"] else "Native skill"
    return f"{label} `{item['codex_skill_name']}`"


def render_codex_commands() -> str:
    rows = [
        "# CODEX_COMMANDS.md",
        "",
        "> Auto-generated by `system/scripts/sync_cli_adapters.py`.",
        "> Source of truth: `.agent/command-registry.json`.",
        "",
        "Codex should resolve slash commands through this table, then load the",
        "matching workflow file from `.agent/workflows/`.",
        "",
        "If the user only provides the GitHub repo URL, clone/open the repo, run",
        "`python3 system/scripts/bootstrap.py --agent --non-interactive --repo-url <url>`,",
        "then route any remaining request through the PM decision router or the",
        "matching slash-command workflow.",
        "",
        "| Command | Workflow | Profile | Promoted Codex Skill |",
        "| --- | --- | --- | --- |",
    ]
    for item in get_command_catalog():
        rows.append(
            f"| `/{item['name']}` | `{item['workflow']}` | "
            f"{str(item['execution_profile']).title()} | {codex_adapter_label(item)} |"
        )
    rows.append("")
    return "\n".join(rows)


def render_agents_md() -> str:
    commands = ", ".join(f"`/{item['name']}`" for item in get_promoted_command_catalog())
    return f"""# AGENTS.md - Beats Agentic PM Harness Codex Adapter

> Thin runtime adapter. Source of truth: `.agent/`.

## Runtime Selection

Use the active runtime and its positively detected capabilities. Do not apply a permanent provider hierarchy or silently switch providers. Model defaults are inherited; local promotions require evaluation evidence. Promoted Codex commands: {commands}.

Resolve the execution profile with `python system/scripts/model_policy.py resolve <command> --json`. Unknown capabilities fail closed, and missing Deep support must produce a visible downgrade warning.

## Startup

On a new Codex session:

1. If the user provides only the GitHub repo URL, clone/open the repo and run `python3 system/scripts/bootstrap.py --agent --non-interactive --repo-url <url>` from the repo root.
2. Read `SETTINGS.md` and `STATUS.md` first when they are relevant to the task.
3. Treat `.agent/` as the source of truth.
4. Resolve a command or skill with `python3 system/scripts/harness_registry.py resolve <target>`.
5. Read the selected workflow or skill, then load no more than five directly relevant candidate sources. Never load a candidate list wholesale or invoke a second router.
6. Keep identity, safety, and routing as a stable prefix; append dynamic evidence afterward and preserve deterministic tool order for cache reuse.
7. Use `compact_operator` narration during execution and the resolved final profile for the deliverable.
8. Translate unsupported primitives only when the active runtime reports the required capability.
9. Write durable outputs and verification traces into the standard local paths so runtime switching stays lossless.

## Action-First Responses

Load and follow `.agent/rules/ACTION_FIRST_OUTPUT.md` for every user-facing
response. Apply it to conversational presentation only. Safety requirements,
explicit user instructions, resolved response profiles, workflow contracts,
artifact schemas, and exact structured-output formats take precedence.

## Markdown Intake

When the user asks to convert a local file to Markdown, or a supported file
enters the intake staging lane, load `.agent/skills/markitdown/SKILL.md` and use
`system/scripts/markdown_intake.py`. Preserve the source file. Keep screenshots
on the existing visual path, and require explicit approval before networked or
billable conversion.

## Codex Browser First

When a task needs a browser for local apps, rendered UI checks, localhost demos, screenshots, click-through validation, or page inspection:

1. Use the Codex in-app Browser first.
2. Keep browser work contained in the Codex session whenever possible.
3. Start local servers with terminal commands when needed, then open and validate the URL in the Codex Browser.
4. Capture screenshots, DOM state, console warnings/errors, and interaction evidence through the Codex Browser whenever possible.
5. Do not default to macOS `open`, Chrome, Edge, Safari, Computer Use, or standalone Playwright before trying the Codex Browser.

Use an external browser only when there is a concrete reason: the user explicitly asks for it, the task needs the user's browser profile/cookies/extensions/SSO, the bug is browser-specific, the Codex Browser is unavailable or cannot reach the target after a reasonable attempt, or the workflow needs browser permissions/downloads/OS integration the Codex Browser cannot provide. State the reason briefly before using the external browser.

## Agent Bootstrap

When starting from a GitHub URL:

```bash
git clone <url>
cd beats-pm-kit
python3 system/scripts/bootstrap.py --agent --non-interactive --repo-url <url>
```

After bootstrap, route the user's first real PM input through `system/scripts/pm_decision_router.py` or the matching slash-command workflow.

## Slash Command Dispatch

If the user's message starts with `/command`:

1. Treat it as an explicit workflow invocation, not general conversation.
2. Resolve it with `system/scripts/harness_registry.py`; `CODEX_COMMANDS.md` is the human-readable index.
3. Read that workflow before doing deeper work.
4. Use the rest of the user's message as workflow input.
5. Follow the workflow even if a natural-language interpretation also seems possible.
6. If the command does not exist, say it is unknown and point the user to `/help`.

## Adapter Policy

Generated runtime folders such as `.codex/`, `.gemini/`, `.claude/`, and `.kilocode/` are local build artifacts and must stay ignored. Regenerate them with:

```bash
python system/scripts/sync_cli_adapters.py
python system/scripts/sync_codex_skill_adapters.py --output-dir <codex-skills-dir>
```
"""


def render_gemini_md() -> str:
    return """# GEMINI.md - Beats Agentic PM Harness Adapter

This file is a thin compatibility entrypoint for Gemini CLI and Antigravity.

The canonical agent contract, workflows, skills, and rules live in `.agent/`.
Load `.agent/rules/GEMINI.md` and `.agent/rules/ACTION_FIRST_OUTPUT.md` first,
then resolve workflows from `.agent/workflows/`.
For file-to-Markdown conversion, load `.agent/skills/markitdown/SKILL.md`.
Generated local adapter directories are intentionally ignored by Git.

If the user provides only the GitHub repo URL, clone/open the repo and run:

```bash
python3 system/scripts/bootstrap.py --agent --non-interactive --repo-url <url>
```

Then route the first real PM input through the PM decision router or the matching workflow.
"""


def render_claude_md() -> str:
    return """# CLAUDE.md - Beats Agentic PM Harness Claude Adapter

Claude Code is a primary harness runtime. This file is its thin entrypoint.

The canonical agent contract, workflows, skills, and rules live in `.agent/`.
Load `.agent/rules/ACTION_FIRST_OUTPUT.md` for every user-facing response.
For file-to-Markdown conversion, load `.agent/skills/markitdown/SKILL.md`.
Run `python system/scripts/sync_cli_adapters.py` to regenerate local Claude command adapters under `.claude/`.
Generated local adapter directories are intentionally ignored by Git.

If the user provides only the GitHub repo URL, clone/open the repo and run:

```bash
python3 system/scripts/bootstrap.py --agent --non-interactive --repo-url <url>
```

Then resolve the first real PM input with `system/scripts/harness_registry.py` and load only the selected bounded workflow context.
"""


def render_omp_config() -> str:
    return """# omp project settings for beats-pm-kit
# Generated locally by `system/scripts/sync_cli_adapters.py`.
#
# Skills: `.claude/skills/` may hold generated thin aliases of the codex
# `beats-*` skills. Disabling the Claude project skill source removes the
# duplicates; the rich versions come from ~/.codex/skills and .agent/skills,
# and remaining .claude entries are mirrored in .opencode/skills.
skills:
  enableClaudeProject: false

# Discovery: gemini/cursor adapter dirs are sync-generated mirrors of .agent/
# and contribute nothing unique to omp sessions. Keep claude (dotcontext MCP,
# slash commands) and codex (beats-* skills, personal guardrails) enabled.
# This only affects omp; Antigravity/Cursor still read their own adapter dirs.
disabledProviders:
  - gemini
  - cursor
"""


IGNORE_MANIFEST = AGENT_DIR / "ignore-manifest.txt"


def load_ignore_patterns() -> list[str]:
    patterns = []
    for line in read_text(IGNORE_MANIFEST).splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            patterns.append(line)
    return patterns


def render_ignore_file(tool: str) -> str:
    header = (
        f"# {tool} ignore patterns\n"
        "# Generated locally by `system/scripts/sync_cli_adapters.py` from\n"
        "# `.agent/ignore-manifest.txt`. Edit the manifest, then rerun the script.\n"
        "\n"
    )
    return header + "\n".join(load_ignore_patterns()) + "\n"


def render_antigravityignore() -> str:
    return render_ignore_file("Antigravity")


def render_cursorignore() -> str:
    return render_ignore_file("Cursor")


def safe_is_dir(path: Path) -> bool:
    try:
        return path.is_dir() and not path.is_symlink()
    except OSError:
        return False


def safe_exists(path: Path) -> bool:
    try:
        return path.exists() or path.is_symlink()
    except OSError:
        return True


def remove_path(path: Path) -> None:
    if not safe_exists(path):
        return
    try:
        if safe_is_dir(path):
            shutil.rmtree(path)
        else:
            path.unlink()
    except FileNotFoundError:
        return
    except OSError:
        shutil.rmtree(path, ignore_errors=True)


def render_summary() -> str:
    return (
        "Adapter sync complete: "
        f"{len(agent_files())} agents, "
        f"{len(workflow_files())} workflows, "
        f"{len(skill_files())} skills."
    )


def main() -> int:
    if not AGENT_DIR.exists():
        print(f"missing canonical .agent directory: {AGENT_DIR}", file=sys.stderr)
        return 1
    if not IGNORE_MANIFEST.exists():
        print(f"missing canonical ignore manifest: {IGNORE_MANIFEST}", file=sys.stderr)
        return 1

    derived_changed = generate_registry_docs.write_generated_files(ROOT)
    generated = {
        ROOT / "AGENTS.md": render_agents_md(),
        ROOT / "CLAUDE.md": render_claude_md(),
        ROOT / "GEMINI.md": render_gemini_md(),
        ROOT / "CODEX_COMMANDS.md": render_codex_commands(),
        ROOT / ".omp" / "config.yml": render_omp_config(),
        ROOT / ".antigravityignore": render_antigravityignore(),
        ROOT / ".cursorignore": render_cursorignore(),
    }

    changed = []
    for path, content in generated.items():
        if write_if_changed(path, content):
            changed.append(relative(path))

    print(render_summary())
    if changed:
        print("Updated files:")
        for path in changed:
            print(f"  - {path}")
    else:
        print("No tracked adapter stubs changed.")
    for path in derived_changed:
        print(f"  - {path}: regenerated from command registry")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
