#!/usr/bin/env python3
"""Generate local CLI adapters from the canonical .agent tree.

The kit treats .agent/ as the source of truth. Runtime-specific adapter files are
thin pointers or local ignored directories so Codex, Gemini, Claude, and Kilo can
run without duplicating the canonical workflow definitions in Git.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
AGENT_DIR = ROOT / ".agent"
sys.path.insert(0, str(ROOT / "system"))

from utils.command_registry import build_command_catalog, get_workflow_descriptions as registry_workflow_descriptions

CORE_ADAPTER_DIRS = {
    ".codex": {
        "agents": AGENT_DIR / "agents",
        "templates": AGENT_DIR / "templates",
        "workflows": AGENT_DIR / "workflows",
    },
    ".gemini": {
        "agents": AGENT_DIR / "agents",
        "skills": AGENT_DIR / "skills",
        "templates": AGENT_DIR / "templates",
        "workflows": AGENT_DIR / "workflows",
    },
    ".kilocode": {
        "agents": AGENT_DIR / "agents",
        "rules": AGENT_DIR / "rules",
        "skills": AGENT_DIR / "skills",
        "templates": AGENT_DIR / "templates",
        "workflows": AGENT_DIR / "workflows",
    },
}

PROMOTED_CODEX_COMMANDS = [
    "boss",
    "create",
    "day",
    "meet",
    "paste",
    "plan",
    "track",
    "transcript",
    "update",
    "vacuum",
    "week",
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        remove_path(path)
    if path.exists() and not path.is_symlink() and read_text(path) == content:
        return False
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    return True


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def workflow_files() -> list[Path]:
    return sorted((AGENT_DIR / "workflows").glob("*.md"))


def skill_files() -> list[Path]:
    return sorted((AGENT_DIR / "skills").glob("*/SKILL.md"))


def agent_files() -> list[Path]:
    return sorted((AGENT_DIR / "agents").glob("*.md"))


def get_workflow_descriptions() -> list[tuple[str, str]]:
    return registry_workflow_descriptions(ROOT)


def get_command_catalog() -> list[dict[str, str | bool]]:
    return build_command_catalog(ROOT)


def codex_adapter_label(item: dict[str, str | bool | list[str]]) -> str:
    if item["codex_promotion"] != "skill":
        return "Dispatch only"
    label = "Guarded skill" if item["dangerous"] else "Native skill"
    return f"{label} `{item['codex_skill_name']}`"


def render_codex_commands() -> str:
    rows = [
        "# CODEX_COMMANDS.md",
        "",
        "> Auto-generated by `system/scripts/sync_cli_adapters.py`.",
        "> Source of truth: `.agent/workflows/`.",
        "",
        "Codex should resolve slash commands through this table, then load the",
        "matching workflow file from `.agent/workflows/`.",
        "",
        "| Command | Workflow | Promoted Codex Skill |",
        "| --- | --- | --- |",
    ]
    for item in get_command_catalog():
        rows.append(f"| `/{item['name']}` | `{item['workflow']}` | {codex_adapter_label(item)} |")
    rows.append("")
    return "\n".join(rows)


def render_agents_md() -> str:
    commands = ", ".join(f"`/{name}`" for name in PROMOTED_CODEX_COMMANDS)
    return f"""# AGENTS.md - Beats PM Kit Codex Adapter

> Thin runtime adapter. Source of truth: `.agent/`.

## Runtime Priority

1. **Antigravity first** - canonical command behavior and orchestration semantics live in `.agent/`.
2. **Codex second** - use native-feeling adapters for the most-used commands: {commands}.
3. **Compatibility CLIs next** - Gemini CLI, Claude Code, and KiloCode generate local adapters from `.agent/` without redefining workflow logic.

## Startup

On a new Codex session:

1. Read `SETTINGS.md` and `STATUS.md` first when they are relevant to the task.
2. Treat `.agent/` as the source of truth.
3. When the user invokes `/command`, resolve it through `CODEX_COMMANDS.md`.
4. Load only the minimum `.agent/workflows/` and `.agent/skills/` files needed for the current task.
5. Translate Antigravity-only primitives into Codex equivalents instead of failing.
6. Write durable outputs back into the standard repo folders so runtime switching stays lossless.

## Slash Command Dispatch

If the user's message starts with `/command`:

1. Treat it as an explicit workflow invocation, not general conversation.
2. Resolve it using `CODEX_COMMANDS.md` or `.agent/workflows/<command>.md`.
3. Read that workflow before doing deeper work.
4. Use the rest of the user's message as workflow input.
5. Follow the workflow even if a natural-language interpretation also seems possible.
6. If the command does not exist, say it is unknown and point the user to `/help`.

## Adapter Policy

Generated runtime folders such as `.codex/`, `.gemini/`, `.claude/`, and `.kilocode/` are local build artifacts and must stay ignored. Regenerate them with:

```bash
python system/scripts/sync_cli_adapters.py
python system/scripts/sync_codex_skill_adapters.py --output <codex-skills-dir>
```
"""


def render_gemini_md() -> str:
    return """# GEMINI.md - Beats PM Kit Runtime Adapter

This file is a thin compatibility entrypoint for Gemini CLI and Antigravity.

The canonical agent contract, workflows, skills, and rules live in `.agent/`.
Load `.agent/rules/GEMINI.md` first, then resolve workflows from `.agent/workflows/`.
Generated local adapter directories are intentionally ignored by Git.
"""


def render_claude_md() -> str:
    return """# CLAUDE.md - Beats PM Kit Claude Adapter

This file is a thin compatibility entrypoint for Claude Code.

The canonical agent contract, workflows, skills, and rules live in `.agent/`.
Run `python system/scripts/sync_cli_adapters.py` to regenerate local Claude command adapters under `.claude/`.
Generated local adapter directories are intentionally ignored by Git.
"""


def render_codex_rules() -> str:
    return """# Codex Runtime Notes

Generated locally by `system/scripts/sync_cli_adapters.py`.

## Slash Command Dispatch

- If the user's first non-whitespace token is `/command`: follow the explicit dispatch rule in `CODEX_COMMANDS.md`.
- Resolve the command to `.agent/workflows/<command>.md` before applying general conversation behavior.
- If no workflow exists, report an unknown command and suggest `/help`.

## Runtime Notes

- Treat `.agent/` as canonical.
- Resolve slash commands through root `CODEX_COMMANDS.md`.
- Prefer promoted Codex skills when present.
- Do not commit generated runtime adapter directories.
"""


def render_claude_runtime() -> str:
    return """# Claude Code Adapter

Generated locally by `system/scripts/sync_cli_adapters.py`.

Use `.agent/` as the source of truth. Claude command files under `.claude/commands/`
should only point back to `.agent/workflows/`.
"""


def render_claude_command(workflow: Path) -> str:
    name = workflow.stem
    return f"""---
description: Run the Beats PM Kit `{name}` workflow.
argument-hint: "[workflow input]"
---

Load `.agent/workflows/{name}.md` and execute it using the user's remaining input:

`$ARGUMENTS`
"""


def safe_is_dir(path: Path) -> bool:
    try:
        return path.is_dir() and not path.is_symlink()
    except OSError:
        return False


def safe_exists(path: Path) -> bool:
    try:
        return path.exists() or path.is_symlink()
    except OSError:
        return True


def remove_path(path: Path) -> None:
    if not safe_exists(path):
        return
    try:
        if safe_is_dir(path):
            shutil.rmtree(path)
        else:
            path.unlink()
    except FileNotFoundError:
        return
    except OSError:
        shutil.rmtree(path, ignore_errors=True)


def copy_file_if_changed(source: Path, destination: Path) -> bool:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if safe_is_dir(destination):
        remove_path(destination)
    if destination.is_symlink():
        remove_path(destination)
    if safe_exists(destination):
        try:
            source_stat = source.stat()
            destination_stat = destination.stat()
            if (
                not destination.is_symlink()
                and source_stat.st_size == destination_stat.st_size
                and source_stat.st_mtime_ns == destination_stat.st_mtime_ns
            ):
                return False
            if not destination.is_symlink() and destination.read_bytes() == source.read_bytes():
                return False
        except OSError:
            remove_path(destination)
    shutil.copy2(source, destination)
    return True


def copy_tree_changed(source: Path, destination: Path) -> int:
    changed = 0
    if safe_exists(destination) and not safe_is_dir(destination):
        remove_path(destination)
        changed += 1
    destination.mkdir(parents=True, exist_ok=True)

    source_entries: set[str] = set()
    for source_item in source.rglob("*"):
        rel = source_item.relative_to(source)
        source_entries.add(rel.as_posix())
        dest_item = destination / rel
        if source_item.is_dir():
            if not safe_is_dir(dest_item):
                remove_path(dest_item)
                dest_item.mkdir(parents=True, exist_ok=True)
                changed += 1
        elif source_item.is_file():
            if copy_file_if_changed(source_item, dest_item):
                changed += 1

    for dest_item in sorted(destination.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        rel = dest_item.relative_to(destination).as_posix()
        if rel not in source_entries:
            remove_path(dest_item)
            changed += 1
    return changed


def normalize_kilocode_agent_frontmatter(content: str) -> str:
    lines = content.splitlines()
    if not lines or lines[0] != "---":
        return content

    normalized: list[str] = []
    in_frontmatter = True
    changed = False
    for index, line in enumerate(lines):
        if index > 0 and line == "---":
            in_frontmatter = False
            normalized.append(line)
            continue
        if in_frontmatter and line.startswith("tools:") and "," in line:
            tools = [tool.strip() for tool in line.split(":", 1)[1].split(",") if tool.strip()]
            normalized.append("tools:")
            normalized.extend(f"  {tool}: true" for tool in tools)
            changed = True
            continue
        normalized.append(line)

    if not changed:
        return content
    suffix = "\n" if content.endswith("\n") else ""
    return "\n".join(normalized) + suffix


def normalize_kilocode_agents(path: Path) -> int:
    if not safe_is_dir(path):
        return 0
    changed = 0
    for agent_file in sorted(path.glob("*.md")):
        normalized = normalize_kilocode_agent_frontmatter(read_text(agent_file))
        if write_if_changed(agent_file, normalized):
            changed += 1
    return changed


def ensure_local_copy(path: Path, target: Path) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if target.is_dir():
        changed = copy_tree_changed(target, path)
        return "unchanged" if changed == 0 else f"synced {changed}"
    changed = copy_file_if_changed(target, path)
    return "updated" if changed else "unchanged"


def sync_runtime_links() -> list[str]:
    messages: list[str] = []
    for adapter, entries in CORE_ADAPTER_DIRS.items():
        for name, target in entries.items():
            status = ensure_local_copy(ROOT / adapter / name, target)
            if adapter == ".kilocode" and name == "agents":
                normalized = normalize_kilocode_agents(ROOT / adapter / name)
                if normalized:
                    status = f"{status}; normalized {normalized}"
            messages.append(f"{adapter}/{name}: {status}")

    commands_dir = ROOT / ".claude" / "commands"
    if safe_exists(commands_dir) and not safe_is_dir(commands_dir):
        remove_path(commands_dir)
    commands_dir.mkdir(parents=True, exist_ok=True)
    for workflow in workflow_files():
        changed = write_if_changed(commands_dir / f"{workflow.stem}.md", render_claude_command(workflow))
        messages.append(f".claude/commands/{workflow.stem}.md: {'updated' if changed else 'unchanged'}")
    return messages


def render_summary() -> str:
    return (
        "Adapter sync complete: "
        f"{len(agent_files())} agents, "
        f"{len(workflow_files())} workflows, "
        f"{len(skill_files())} skills."
    )


def main() -> int:
    if not AGENT_DIR.exists():
        print(f"missing canonical .agent directory: {AGENT_DIR}", file=sys.stderr)
        return 1

    generated = {
        ROOT / "AGENTS.md": render_agents_md(),
        ROOT / "CLAUDE.md": render_claude_md(),
        ROOT / "GEMINI.md": render_gemini_md(),
        ROOT / "CODEX_COMMANDS.md": render_codex_commands(),
        ROOT / ".codex" / "rules.md": render_codex_rules(),
        ROOT / ".claude" / "CLAUDE.md": render_claude_runtime(),
        ROOT / ".gemini" / "GEMINI.md": render_gemini_md(),
    }

    changed = []
    for path, content in generated.items():
        if write_if_changed(path, content):
            changed.append(relative(path))

    link_messages = sync_runtime_links()
    print(render_summary())
    if changed:
        print("Updated files:")
        for path in changed:
            print(f"  - {path}")
    else:
        print("No tracked adapter stubs changed.")
    for message in link_messages:
        print(f"  - {message}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
